version: 0.0
os: linux
files:
  - source: paws-pets.tar.gz
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh.sh
      timeout: 3600
      runas: root
  ValidateService:
    - location: scripts/check_container.sh
      timeout: 3600
      runas: root