version: 0.2

phases:
  install:
    commands:
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i2c7a5l2
  build:
    commands:
      - mvn install
      - docker build -t paws-pets-joao-braga .
      - docker save paws-pets-joao-braga | gzip > paws-pets-joao-braga.tar.gz
      - docker tag paws-pets-joao-braga:latest public.ecr.aws/i2c7a5l2/paws-pets-joao-braga:latest
  post_build:
    commands:
      - docker push public.ecr.aws/i2c7a5l2/paws-pets-joao-braga:latest
artifacts:
  files:
    - 'target/*.jar'
    - 'appspec.yml'
    - 'scripts/**/*'
    - 'paws-pets-joao-braga.tar.gz'